import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const settingsPagePath = resolve('src/pages/SettingsPage.vue')
const zhCnLocalePath = resolve('src/i18n/locales/zh-CN.ts')

// After the i18n refactor, Chinese UI copy lives in `src/i18n/locales/zh-CN.ts`
// and the .vue source now references it via `t('settings.*')`. To keep these
// "model contract" tests meaningful, split the file content into:
//   * `source`     — the .vue source plus the zh-CN catalog. Use for positive
//                    assertions (`toContain`) of UI strings and code shapes.
//   * `sourceOnly` — the .vue source alone. Use for negative assertions
//                    (`not.toContain`) that guard against regressing removed
//                    features/legacy copy.
const source = readFileSync(settingsPagePath, 'utf8') + '\n' + readFileSync(zhCnLocalePath, 'utf8')
const sourceOnly = readFileSync(settingsPagePath, 'utf8')

describe('SettingsPage model editor layout', () => {
  it('renders an API Switch style channel modal instead of separate model interface sections', () => {
    expect(source).toContain('const modelEditorTitle = computed(() =>')
    expect(source).toContain('data-testid="api-channel-editor-modal"')
    expect(source).toContain('const channelPresets')
    expect(source).toContain('const channelBaseUrlPresets')
    expect(source).toContain('const autoApiTypeSummary = computed')
    expect(source).toContain('settings.apiType')
    expect(source).toContain('settings.autoDetect')
    expect(source).toContain('model-draft-note-unified')
    expect(source).toContain('channel-model-panel')
    expect(source).toContain('refreshChannelModelCatalog')
    expect(source).toContain('model-draft-name-unified')
    expect(source).toContain('model-draft-kind-unified')
    expect(source).toContain("type ChannelDefaultModelKind = 'all' | ModelProfile['kind']")
    expect(source).toContain("const channelDefaultModelKind = ref<ChannelDefaultModelKind>('all')")
    expect(source).toContain('function applyDefaultModelKind')
    expect(source).toContain('settings.allModels')
    expect(source).toContain('model-draft-endpoint-unified')
    expect(source).toContain('model-draft-base-url-preset')
    expect(source).toContain('common.save')
    expect(sourceOnly).not.toContain('Header 注入配置')
    expect(sourceOnly).not.toContain('channel-header-tabs')
    expect(sourceOnly).not.toContain('model-draft-protocol-unified')
    expect(sourceOnly).not.toContain('model-draft-api-path-unified')
    expect(sourceOnly).not.toContain('provider-list-panel')
    expect(sourceOnly).not.toContain('data-testid="image-model-card"')
    expect(sourceOnly).not.toContain('data-testid="video-model-card"')
    expect(sourceOnly).not.toContain('data-testid="text-model-card"')
    expect(sourceOnly).not.toContain('isCreatingModel')
    expect(sourceOnly).not.toContain('modelCatalogOpen')
  })

  it('treats configured endpoints as base URLs without requiring a manual v1 path', () => {
    expect(source).toContain("path: 'v1/chat/completions'")
    expect(source).toContain("path: 'v1/images/generations'")
    expect(source).toContain('OpenAI 通用标准')
    expect(source).toContain('Anthropic 协议')
    expect(source).toContain('阿里云通义万相')
    expect(source).toContain('芒果 AIGC 分镜生图')
    expect(source).toContain('openapi/v1/storyboard/generateByPromptV2')
    expect(source).toContain('Secret Key')
    expect(source).toContain('mgtv-storyboard')
    expect(source).toContain('api/v1/services/aigc/multimodal-generation/generation')
    expect(source).toContain('Agnes Video')
    expect(source).toContain('agnes-video')
    expect(source).toContain('Base URL')
    expect(source).toContain("'https://api.openai.com'")
    expect(source).toContain("'https://apihub.agnes-ai.com'")
    expect(source).toContain('https://your-relay.example.com')
    expect(sourceOnly).not.toContain('https://aigc.mgtv.com')
    expect(sourceOnly).not.toContain('model: defaultModel')
    expect(sourceOnly).not.toContain("endpoint: 'https://api.openai.com/v1")
  })

  it('uses channel and base-url presets instead of manual api type and headers', () => {
    expect(source).toContain("{ id: 'openai', label: 'OpenAI', name: 'OpenAI', endpoint: 'https://api.openai.com' }")
    expect(source).toContain("{ id: 'agnes', label: 'Agnes', name: 'Agnes', endpoint: 'https://apihub.agnes-ai.com' }")
    expect(source).toContain("{ id: 'third-party', label: t('settings.channelThirdParty'), name: t('settings.channelThirdParty'), endpoint: '' }")
    expect(source).toContain('function inferApiProtocol')
    expect(source).toContain('function syncAutoApiType')
    expect(source).toContain('function applyChannelPreset')
    expect(source).toContain('function applyBaseUrlPreset')
    expect(source).toContain("draft.value.name = channelPresets.find((item) => item.id === preset.id)?.name ?? draft.value.name")
    expect(source).toContain('function resolvedDraftChannelName')
    expect(source).toContain('store.replaceModelsForEndpoint(draft.value.endpoint, profiles')
    expect(sourceOnly).not.toContain('function parseChannelHeaders')
    expect(sourceOnly).not.toContain('applyHeaderPreset')
  })

  it('does not show builtin fallback models in the remote model picker', () => {
    expect(sourceOnly).not.toContain('builtinModelCatalog')
    expect(sourceOnly).not.toContain('内置兜底')
    expect(sourceOnly).not.toContain('当前显示内置常用模型')
    expect(sourceOnly).not.toContain('[量]')
    expect(source).toContain('type="checkbox"')
    expect(source).toContain('@click="selectAllChannelModels"')
    expect(source).toContain(':checked="selectedCatalogModelIds.has(item.model)"')
    expect(source).toContain('@change="toggleChannelModel(item, $event)"')
    expect(source).toContain('接口未返回模型')
  })

  it('marks API catalog fetch results as a connection check', () => {
    expect(source).toContain('setSelectedChannelModels(channelSelectableModelOptions.value)')
    expect(source).toContain("draft.value.status = remoteModels.length ? 'connected' : 'failed'")
    expect(source).toContain('draft.value.lastCheckedAt = new Date().toISOString()')
    expect(source).toContain('selectedChannelModelCount.value')
  })

  it('saves selected catalog models as routed model profiles', () => {
    expect(source).toContain('const selectedChannelModels = computed')
    expect(source).toContain('const channelSelectableModelOptions = computed<ModelCatalogEntry[]>(() =>')
    expect(source).toContain('const defaultKindModelCatalog = computed(() => remoteModelCatalog.value.filter')
    expect(source).toContain("channelDefaultModelKind.value === 'all' || item.kind === channelDefaultModelKind.value")
    expect(source).toContain('function modelProfileFromCatalogItem')
    expect(source).toContain('const profiles = selectedChannelModels.value.map((item) => modelProfileFromCatalogItem(item))')
    expect(source).toContain('profiles.length')
    expect(source).toContain('id: existing?.id ?? createId(\'model\')')
    expect(sourceOnly).not.toContain('index === 0 && store.models.some((model) => model.id === draft.value.id)')
  })

  it('shows a per-model loading state while testing connection', () => {
    expect(source).toContain('const testingModelIds = ref<Set<string>>(new Set())')
    expect(source).toContain('async function testModelConnection(id: string)')
    expect(source).toContain(':disabled="isModelTesting(entry.profile.id)"')
    expect(source).toContain(':aria-busy="isModelTesting(entry.profile.id)"')
    expect(source).toContain('isModelTesting(entry.profile.id)')
    expect(source).toContain('settings.test')
    expect(source).toContain('settings.testing')
    expect(sourceOnly).not.toContain('@click="store.testModel(model.id)"')
  })

  it('renders model management without duplicate create or bulk-test actions', () => {
    expect(source).toContain("const managedModels = computed(() => store.models.filter((model) => model.provider !== 'local-preview'))")
    expect(source).toContain('const filteredManagedModelGroups = computed(() =>')
    expect(source).toContain('data-testid="model-management-panel"')
    expect(source).toContain('data-testid="managed-model-row"')
    expect(source).toContain('v-for="group in filteredManagedModelGroups"')
    expect(source).toContain('modelRouteGroupMetaLine(group)')
    expect(source).toContain('modelRouteGroupChannelSummary(group)')
    expect(source).toContain("const modelManagerKindTabs: Array<{ value: ModelProfile['kind']; label: string }>")
    expect(source).toContain('function toggleModelManagerKindFilter')
    expect(source).toContain('@click="toggleModelManagerKindFilter(tab.value)"')
    expect(source).toContain('点击新增渠道创建上游配置')
    expect(sourceOnly).not.toContain("{ value: 'all', label: 'auto' }")
    expect(sourceOnly).not.toContain('Shift+Click：全开/全关，Ctrl+Click：置顶')
    expect(sourceOnly).not.toContain('model-management-actions')
    expect(sourceOnly).not.toContain('model-test-all-button')
    expect(sourceOnly).not.toContain('@click="testAllConfiguredModels"')
    expect(sourceOnly).not.toContain('@click="editModel(model)"')
    expect(sourceOnly).not.toContain('@click="testModelConnection(model.id)"')
    expect(sourceOnly).not.toContain('removeModelWithConfirmation')
    expect(sourceOnly).not.toContain('setPrimaryManagedModel')
    expect(sourceOnly).not.toContain('新增模型')
    expect(sourceOnly).not.toContain('暂无可测速')
    expect(sourceOnly).not.toContain('暂无可测试')
    expect(sourceOnly).not.toContain('连接检测')
    expect(sourceOnly).not.toContain('检测全部')
  })

  it('renders API upstreams as an API Switch style channel table', () => {
    expect(source).toContain('const savedApiRouteGroups = computed<ModelRouteGroup[]>(() => store.modelRouteGroups.filter((group) => group.profiles.length))')
    expect(source).toContain('const autoRouteGroupCount = computed(() => savedApiRouteGroups.value.filter((group) => group.profiles.length > 1).length)')
    expect(source).toContain('type ApiChannelEntry = {')
    expect(source).toContain('const savedApiChannelEntries = computed<ApiChannelEntry[]>(() =>')
    expect(source).toContain('const activeApiChannelEntry = computed(() =>')
    expect(source).toContain('data-testid="api-route-groups"')
    expect(source).toContain('data-testid="api-channel-table"')
    expect(source).toContain('settings.apiChannels')
    expect(source).toContain('settings.colChannelName')
    expect(source).toContain('settings.colApiType')
    expect(source).toContain('settings.colBaseUrl')
    expect(source).toContain('settings.colStatus')
    expect(source).toContain('settings.colResponse')
    expect(source).toContain('settings.colModelCount')
    expect(source).toContain('v-for="entry in savedApiChannelEntries"')
    expect(source).toContain('apiChannelName(profile)')
    expect(source).toContain('routeCatalogUrl(entry.profile)')
    expect(source).toContain('apiChannelModelCountLabel(entry)')
    expect(source).toContain('@click="selectApiChannel(entry)"')
    expect(source).toContain('@click="editModel(entry.profile)"')
    expect(source).toContain('@click="testModelConnection(entry.profile.id)"')
    expect(source).toContain('@click="removeApiChannelWithConfirmation(entry)"')
    expect(sourceOnly).not.toContain('v-for="group in savedApiRouteGroups"')
    expect(sourceOnly).not.toContain('const savedApiRouteEntries = computed<ApiRouteEntry[]>')
  })

  it('renders model configuration as a clean gotbot provider console', () => {
    expect(source).toContain('data-testid="cc-switch-model-config"')
    expect(source).toContain('<strong>gotbot</strong>')
    expect(source).toContain('model-console-header')
    expect(source).toContain('model-console-summary')
    expect(source).toContain('aria-label="渠道操作"')
    expect(source).toContain('settings.addChannel')
    expect(sourceOnly).not.toContain('Gotbot Switch')
    expect(sourceOnly).not.toContain('window-dots')
    expect(sourceOnly).not.toContain('model-console-chrome')
    expect(sourceOnly).not.toContain('console-app-button image')
    expect(sourceOnly).not.toContain('console-app-button video')
    expect(sourceOnly).not.toContain('console-app-button text')
    expect(sourceOnly).not.toContain('console-app-button tts')
  })

  it('removes redundant image video text and tts model interface panels', () => {
    expect(sourceOnly).not.toContain('图像模型\n')
    expect(sourceOnly).not.toContain('视频模型\n')
    expect(sourceOnly).not.toContain('文本模型（润色提示词）')
    expect(sourceOnly).not.toContain('语音模型\n')
    expect(sourceOnly).not.toContain('<button class="btn-soft add-row-btn"')
    expect(sourceOnly).not.toContain('grid-template-columns: minmax(210px, 1.25fr) minmax(240px, 1fr);')
  })

  it('still wires the system settings card with default format, logout and reset actions', () => {
    expect(source).toContain('settings.defaultExportFormat')
    expect(source).toContain('function logoutAccount')
    expect(source).toContain('store.logout()')
    expect(source).toContain("router.replace('/login')")
    expect(source).toContain('settings.logout')
  })

  it('exposes a safe, read-only default export directory control with picker and reset', () => {
    // The directory field is read-only; editing the value directly is no longer possible
    // (previously it was an editable input bound with v-model).
    expect(source).toContain('id="default-export-dir"')
    expect(source).toContain('readonly')
    expect(source).toContain('function chooseExportDirectory')
    expect(source).toContain('function resetExportDirectory')
    expect(source).toContain('settings.defaultExportDir')
    expect(source).toContain('settings.chooseExportDir')
    expect(source).toContain('settings.exportDirFollowSystem')
    // 中文「默认导出目录」字面量只应出现在 zh-CN 目录中,不再直接写在 .vue 源码里
    expect(sourceOnly).not.toContain('默认输出目录')
    // 旧式可直接编辑 + `chooseDefaultOutputDir` API 已删除
    expect(sourceOnly).not.toContain('id="default-output-dir"')
    expect(sourceOnly).not.toContain('chooseDefaultOutputDir')
  })
})
