import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const settingsPagePath = resolve('src/pages/SettingsPage.vue')

describe('SettingsPage model editor layout', () => {
  it('renders an API Switch style channel modal instead of separate model interface sections', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain('const modelEditorTitle = computed(() =>')
    expect(source).toContain('data-testid="api-channel-editor-modal"')
    expect(source).toContain('const channelPresets')
    expect(source).toContain('const channelBaseUrlPresets')
    expect(source).toContain('const autoApiTypeSummary = computed')
    expect(source).toContain('API 类型</span>')
    expect(source).toContain('自动检测')
    expect(source).toContain('model-draft-note-unified')
    expect(source).toContain('channel-model-panel')
    expect(source).toContain('refreshChannelModelCatalog')
    expect(source).toContain('model-draft-name-unified')
    expect(source).toContain('model-draft-kind-unified')
    expect(source).toContain("type ChannelDefaultModelKind = 'all' | ModelProfile['kind']")
    expect(source).toContain("const channelDefaultModelKind = ref<ChannelDefaultModelKind>('all')")
    expect(source).toContain('function applyDefaultModelKind')
    expect(source).toContain('<option value="all">全部模型</option>')
    expect(source).toContain('model-draft-endpoint-unified')
    expect(source).toContain('model-draft-base-url-preset')
    expect(source).toContain('保存</button>')
    expect(source).not.toContain('Header 注入配置')
    expect(source).not.toContain('channel-header-tabs')
    expect(source).not.toContain('model-draft-protocol-unified')
    expect(source).not.toContain('model-draft-api-path-unified')
    expect(source).not.toContain('provider-list-panel')
    expect(source).not.toContain('data-testid="image-model-card"')
    expect(source).not.toContain('data-testid="video-model-card"')
    expect(source).not.toContain('data-testid="text-model-card"')
    expect(source).not.toContain('isCreatingModel')
    expect(source).not.toContain('modelCatalogOpen')
  })

  it('treats configured endpoints as base URLs without requiring a manual v1 path', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain("path: 'v1/chat/completions'")
    expect(source).toContain("path: 'v1/images/generations'")
    expect(source).toContain('OpenAI 通用标准')
    expect(source).toContain('Anthropic 协议')
    expect(source).toContain('阿里云通义万相')
    expect(source).toContain('芒果 AIGC 分镜生图')
    expect(source).toContain('openapi/v1/storyboard/generateByPromptV2')
    expect(source).toContain('Secret Key')
    expect(source).toContain('mgtv-storyboard')
    expect(source).toContain('api/v1/services/aigc/multimodal-generation/generation')
    expect(source).toContain('Agnes Video')
    expect(source).toContain('agnes-video')
    expect(source).toContain('Base URL')
    expect(source).toContain("'https://api.openai.com'")
    expect(source).toContain("'https://apihub.agnes-ai.com'")
    expect(source).toContain('https://your-relay.example.com')
    expect(source).not.toContain('https://aigc.mgtv.com')
    expect(source).not.toContain('model: defaultModel')
    expect(source).not.toContain("endpoint: 'https://api.openai.com/v1")
  })

  it('uses channel and base-url presets instead of manual api type and headers', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain("{ id: 'openai', label: 'OpenAI', name: 'OpenAI', endpoint: 'https://api.openai.com' }")
    expect(source).toContain("{ id: 'agnes', label: 'Agnes', name: 'Agnes', endpoint: 'https://apihub.agnes-ai.com' }")
    expect(source).toContain("{ id: 'third-party', label: '第三方接口', name: '第三方接口', endpoint: '' }")
    expect(source).toContain('function inferApiProtocol')
    expect(source).toContain('function syncAutoApiType')
    expect(source).toContain('function applyChannelPreset')
    expect(source).toContain('function applyBaseUrlPreset')
    expect(source).toContain("draft.value.name = channelPresets.find((item) => item.id === preset.id)?.name ?? draft.value.name")
    expect(source).toContain('function resolvedDraftChannelName')
    expect(source).toContain('store.replaceModelsForEndpoint(draft.value.endpoint, profiles')
    expect(source).not.toContain('function parseChannelHeaders')
    expect(source).not.toContain('applyHeaderPreset')
  })

  it('does not show builtin fallback models in the remote model picker', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).not.toContain('builtinModelCatalog')
    expect(source).not.toContain('内置兜底')
    expect(source).not.toContain('当前显示内置常用模型')
    expect(source).not.toContain('[量]')
    expect(source).toContain('type="checkbox"')
    expect(source).toContain('@click="selectAllChannelModels">全选')
    expect(source).toContain(':checked="selectedCatalogModelIds.has(item.model)"')
    expect(source).toContain('@change="toggleChannelModel(item, $event)"')
    expect(source).toContain('接口未返回模型')
  })

  it('marks API catalog fetch results as a connection check', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain('setSelectedChannelModels(channelSelectableModelOptions.value)')
    expect(source).toContain("draft.value.status = remoteModels.length ? 'connected' : 'failed'")
    expect(source).toContain('draft.value.lastCheckedAt = new Date().toISOString()')
    expect(source).toContain('当前勾选 ${selectedChannelModelCount.value} 个${channelDefaultKindLabel()}')
  })

  it('saves selected catalog models as routed model profiles', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain('const selectedChannelModels = computed')
    expect(source).toContain('const channelSelectableModelOptions = computed<ModelCatalogEntry[]>(() =>')
    expect(source).toContain('const defaultKindModelCatalog = computed(() => remoteModelCatalog.value.filter')
    expect(source).toContain("channelDefaultModelKind.value === 'all' || item.kind === channelDefaultModelKind.value")
    expect(source).toContain('function modelProfileFromCatalogItem')
    expect(source).toContain('const profiles = selectedChannelModels.value.map((item) => modelProfileFromCatalogItem(item))')
    expect(source).toContain('已同步 ${profiles.length} 个模型到模型管理')
    expect(source).toContain('id: existing?.id ?? createId(\'model\')')
    expect(source).not.toContain('index === 0 && store.models.some((model) => model.id === draft.value.id)')
  })

  it('shows a per-model loading state while testing connection', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain('const testingModelIds = ref<Set<string>>(new Set())')
    expect(source).toContain('async function testModelConnection(id: string)')
    expect(source).toContain(':disabled="isModelTesting(entry.profile.id)"')
    expect(source).toContain(':aria-busy="isModelTesting(entry.profile.id)"')
    expect(source).toContain("{{ isModelTesting(entry.profile.id) ? '检测中' : '检测' }}")
    expect(source).not.toContain('@click="store.testModel(model.id)"')
  })

  it('renders model management without duplicate create or bulk-test actions', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain("const managedModels = computed(() => store.models.filter((model) => model.provider !== 'local-preview'))")
    expect(source).toContain('const filteredManagedModels = computed(() =>')
    expect(source).toContain('data-testid="model-management-panel"')
    expect(source).toContain('data-testid="managed-model-row"')
    expect(source).toContain('setPrimaryManagedModel(model)')
    expect(source).toContain("const modelManagerKindTabs: Array<{ value: ModelProfile['kind']; label: string }>")
    expect(source).toContain('function toggleModelManagerKindFilter')
    expect(source).toContain('@click="toggleModelManagerKindFilter(tab.value)"')
    expect(source).toContain('点击新增渠道创建上游配置')
    expect(source).not.toContain("{ value: 'all', label: 'auto' }")
    expect(source).not.toContain('Shift+Click：全开/全关，Ctrl+Click：置顶')
    expect(source).not.toContain('model-management-actions')
    expect(source).not.toContain('model-test-all-button')
    expect(source).not.toContain('@click="testAllConfiguredModels"')
    expect(source).not.toContain('新增模型')
    expect(source).not.toContain('暂无可测速')
    expect(source).not.toContain('暂无可测试')
    expect(source).not.toContain('连接检测')
    expect(source).not.toContain('检测全部')
  })

  it('renders API upstreams as an API Switch style channel table', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain('const savedApiRouteGroups = computed<ModelRouteGroup[]>(() => store.modelRouteGroups.filter((group) => group.profiles.length))')
    expect(source).toContain('const autoRouteGroupCount = computed(() => savedApiRouteGroups.value.filter((group) => group.profiles.length > 1).length)')
    expect(source).toContain('type ApiChannelEntry = {')
    expect(source).toContain('const savedApiChannelEntries = computed<ApiChannelEntry[]>(() =>')
    expect(source).toContain('const activeApiChannelEntry = computed(() =>')
    expect(source).toContain('data-testid="api-route-groups"')
    expect(source).toContain('data-testid="api-channel-table"')
    expect(source).toContain('API 渠道')
    expect(source).toContain('<th>渠道名称</th>')
    expect(source).toContain('<th>API 类型</th>')
    expect(source).toContain('<th>Base URL</th>')
    expect(source).toContain('<th>状态</th>')
    expect(source).toContain('<th>响应</th>')
    expect(source).toContain('<th>模型数</th>')
    expect(source).toContain('v-for="entry in savedApiChannelEntries"')
    expect(source).toContain('apiChannelName(profile)')
    expect(source).toContain('routeCatalogUrl(entry.profile)')
    expect(source).toContain('apiChannelModelCountLabel(entry)')
    expect(source).toContain('@click="selectApiChannel(entry)"')
    expect(source).toContain('@click="editModel(entry.profile)"')
    expect(source).toContain('@click="testModelConnection(entry.profile.id)"')
    expect(source).toContain('@click="removeApiChannelWithConfirmation(entry)"')
    expect(source).not.toContain('v-for="group in savedApiRouteGroups"')
    expect(source).not.toContain('const savedApiRouteEntries = computed<ApiRouteEntry[]>')
  })

  it('renders model configuration as a clean gotbot provider console', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain('data-testid="cc-switch-model-config"')
    expect(source).toContain('<strong>gotbot</strong>')
    expect(source).toContain('model-console-header')
    expect(source).toContain('model-console-summary')
    expect(source).toContain('aria-label="渠道操作"')
    expect(source).toContain('新增渠道')
    expect(source).not.toContain('Gotbot Switch')
    expect(source).not.toContain('window-dots')
    expect(source).not.toContain('model-console-chrome')
    expect(source).not.toContain('console-app-button image')
    expect(source).not.toContain('console-app-button video')
    expect(source).not.toContain('console-app-button text')
    expect(source).not.toContain('console-app-button tts')
  })

  it('removes redundant image video text and tts model interface panels', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).not.toContain('图像模型\\n')
    expect(source).not.toContain('视频模型\\n')
    expect(source).not.toContain('文本模型（润色提示词）')
    expect(source).not.toContain('语音模型\\n')
    expect(source).not.toContain('<button class="btn-soft add-row-btn"')
    expect(source).not.toContain('grid-template-columns: minmax(210px, 1.25fr) minmax(240px, 1fr);')
  })

  it('hides local output directory controls from system settings', () => {
    const source = readFileSync(settingsPagePath, 'utf8')

    expect(source).toContain('默认导出格式')
    expect(source).not.toContain('默认输出目录')
    expect(source).not.toContain('id="default-output-dir"')
    expect(source).not.toContain('chooseDefaultOutputDir')
    expect(source).not.toContain('pickDirectory')
  })
})
